### ISSUE TITLE
Connect to multiple Prismic repositories

### ISSUE THREAD

**Issue by mindmergedesign** [prismicio/gatsby#145]
I was wondering if it is possible to connect to multiple Prismic repositories with this plugin.

**Comment by angeloashmore** [comment]
Hi @mindmergedesign, you should be able to have multiple instances of the plugin, one for each repository.

The only limitation would be the custom type names. If two repositories implemented a Page custom type, the GraphQL types would conflict since they would both be called `PrismicPage`.

If this is an issue for your specific use-case, we could add an option to namespace the types. Something like:

```js
{
  "repository": "my-repo",
  "namespaceTypes": true,
}

// PrismicPage is now PrismicMyRepoPage or something similar
```

**Comment by mindmergedesign** [comment]
@angeloashmore thanks for the reply. I believe adding the option to namespace the types is a great idea. Is that already part of the plugin or is it something that needs to be implemented in a future release?

**Comment by angeloashmore** [comment]
This would have to be implemented in a future release, but the implementation should be straightforward. My primary focus is to get V3 out the door with its current feature set, but this can be added to the roadmap.

Is this a blocking issue for you right now?

**Comment by angeloashmore** [comment]
This is now a feature of the just released v4! Using the new `typePrefix` plugin option allows you to include multiple instances of `gatsby-source-prismic`, each with a unique `typePrefix` value.

See the official documentation for an example: https://prismic.io/docs/technologies/install-the-plugin-gatsby
