### ISSUE TITLE
Previews with static queries

### ISSUE THREAD

**Issue by madeleineostoja** [prismicio/gatsby#218]
Trying to wrap my head around how I'd setup Prismic previews for data used in static queries (eg: site globals like footers). 

I've setup previews with a hook that looks something like this 

```js
export function usePreview(data) {
  if (typeof window === 'undefined' || !window.__PRISMIC_PREVIEW_DATA__) {
    return data;
  }

  return mergePrismicPreviewData({
    data,
    previewData: window.__PRISMIC_PREVIEW_DATA__
  });
}
```

And a `/preview` page that is pretty much straight out of the docs. But obviously when I try to load a page it complains that the preview data I'm giving it doesn't exist on that page, which is true (I have a `settings` document in Prismic for globals). Is there any way I could make this work? I'm still pretty fuzzy on Prismic previews.

**Comment by asyarb** [comment]
This may sound a little silly, but can you try and pass `data` to `mergePrismicPreviewData` as `staticData`?

```js
return mergePrismicPreviewData({
  staticData: data,
  previewData: window.__PRISMIC_PREVIEW_DATA__
});
```

`mergePrismicPreviewData` returns early if either `staticData` or `previewData` is `undefined` since there isn't anything to merge. In this case, it would always return just your preview data resulting in data from a static query appearing to be unavailable.

**Comment by angeloashmore** [comment]
In addition to the name change @asyarb suggests, you may need custom `pathResolver` functionality to tell `usePrismicPreview` where your global Settings document should route to. This is because your global Settings document likely does not have an associated generated page

For general settings, the homepage may make a good landing page:

```js
// linkResolver should be the same function provided to gatsby-config.js
import { linkResolver } from '../linkResolver'

const { previewData, path } = usePrismicPreview({
  repositoryName: 'repoName',
  linkResolver,
  pathResolver: ({ node, key, value }) => doc => {
    if (doc.type === 'settings') return '/'

    return linkResolver({ node, key, value })(doc)
  }
})
```

`path` will be `"/"` if the user is previewing the Settings document. Otherwise, it will fall back to the link resolver value.

**Comment by seaneking** [comment]
Thanks @asyarb and @angeloashmore! Passing `staticData` rather than `data` fixed the error, but I still can't preview actual changes, it just reverts to live content in static queries.

And yep, I've added a case for redirecting settings to home in my resolver so that's all good

**Comment by veloce** [comment]
@seaneking can you precise from what document you are previewing the changes from prismic (where you click the preview button)? 

If I understand things correctly, the preview system in this plugin has been designed to work with page previews and is limited to see one draft at a time by directly navigating to the page you want to preview. So for instance if you are expecting to see the changes in the layout where you have that static query while previewing the home page it won't work, because only preview data for the home page will load. And since your "settings" document doesn't probably link to a page that you can navigate to (it's for global data), you won't be able to see the changes.

**Comment by seaneking** [comment]
Yep I’m previewing changes in a settings document, which is used on every page. For example in one project we have a global CTA banner at the bottom of every page, which is defined in this settings document, and currently there’s no way to preview it.

**Comment by gabrielloeb** [comment]
Not sure what the difference might be, but using context has been working for me in this kind of situation:

```javascript
// gatsby-browser.js
export const wrapPageElement = ({ element, props }) => (
  <Preview>
    <Layout {...props}>{element}</Layout>
  </Preview>
)
```

```jsx
// /components/preview.jsx
const Preview = ({ children }) {
  const preview = usePrismicPreview({
    repositoryName: `myRepository`,
  })

  return (
    <PreviewContext.Provider value={preview}>
      {children}
    </PreviewContext.Provider>
  )
}
```

```javascript
// Every static query
function useFooterData() {
  const staticData = useStaticQuery(prismicFooterQuery)
  return usePreviewData(staticData)
}

function usePreviewData(staticData) {
  const { previewData } = useContext(PreviewContext),
        mergedData = useMemo(
          () => mergePrismicPreviewData({ staticData, previewData }),
          [staticData, previewData]
        )

  return mergedData
}
```

**Comment by jevenson** [comment]
@gabrielloeb Where are you creating the context?

**Comment by gabrielloeb** [comment]
I'm exporting it from `/context/index.tsx`. I don't know what's idiomatic in that regard, but you should be able to create it anywhere. I could share a more robust example if it's useful, let me know.

**Comment by tjjjwxzq** [comment]
How is previewing static queries supposed to work now with the new `gatsby-plugin-prismic-previews` in v4? The docs only show examples for page templates.

**Comment by angeloashmore** [comment]
Hey @tjjjwxzq, good question! We need to add an example of this in the documentation.

You can use the `useMergePrismicPreviewData` hook from `gatsby-plugin-prismic-previews`.

Technical documentation for the hook is available here: https://prismic.io/docs/technologies/gatsby-plugin-prismic-previews-technical-reference#usemergeprismicpreviewdata

Here is an example:

```javascript
import * as React from 'react'
import { useStaticQuery, graphql } from 'gatsby'
import { useMergePrismicPreviewData } from 'gatsby-plugin-prismic-previews'

const NonPageComponent = () => {
  const staticData = useStaticQuery(graphql`
    query NonPageQuery {
      prismicSettings {
        _previewable
        data {
          site_title {
            text
          }
        }
      }
    }
  `)
  const data = useMergePrismicPreviewData(staticData)

  return (
    <h1>
      {data.prismicSettings.data.site_title.text}
    </h1>
  )
}

export default NonPageComponent
```

**Comment by angeloashmore** [comment]
I'm going to close this issue since there is a standard way of doing this now: `useMergePrismicPreviewData`

**Comment by tjjjwxzq** [comment]
Thanks @angeloashmore 🙏
