### ISSUE TITLE
Share link not working for unpublished entry

### ISSUE THREAD

**Issue by rootion** [prismicio/gatsby#276]
I have previews working as expected with both published and unpublished entries.
Prismic toolbar is visible and it gives me the option to share link, but the share link doesn't work if its an unpublished entry; it redirects to 404. If I click on the eye icon of the unpublished entry in prismic, I can see the unpublished preview, but not via the share link.

**Comment by angeloashmore** [comment]
It looks like share links don't work at all for me, even for published pages.

Share links bypass the preview resolver page (e.g. `/preview`) and go straight to the resolved page. Because it skips the preview resolver, the preview data is never fetched.

Share links provide a unique cookie which we could use to detect if preview data should be fetched. We would not know which document is being previewed, however.

For now, share links are unsupported.

**Comment by NeversSync** [comment]
Any updates regarding this issue?

**Comment by angeloashmore** [comment]
Hi @NeversSync, yes, the next version of the plugin will support share links and other features of the Prismic toolbar like auto refreshing on saved drafts.

We don't have an ETA for when it will be available, but we are working on getting a public beta as soon as possible.

You can read more about V4 here: https://github.com/angeloashmore/gatsby-source-prismic/issues/307
And you can see the development branch here: https://github.com/angeloashmore/gatsby-source-prismic/tree/alpha

Thanks!

**Comment by NeversSync** [comment]
@angeloashmore Great, thank you for the update! Looking forward to V4 :)

**Comment by angeloashmore** [comment]
V4 has been published!

[`gatsby-plugin-prismic-previews`](https://github.com/prismicio/gatsby/tree/main/packages/gatsby-plugin-prismic-previews) supports Preview Share links via the Prismic Toolbar.
